grafana:
  enabled: true

  adminUser: admin
  adminPassword: "change-me-strong-password"

  service:
    type: ClusterIP
    port: 80

  ingress:
    enabled: false

  persistence:
    enabled: false

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

alertmanager:
  enabled: true

  ingress:
    enabled: false

  alertmanagerSpec:
    replicas: 1

    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: nvme.network-drives.csi.timeweb.cloud
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi

    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 300m
        memory: 256Mi

prometheus:
  ingress:
    enabled: false

  prometheusSpec:
    replicas: 1
    retention: 24h

    resources:
      requests:
        cpu: 300m
        memory: 1Gi
      limits:
        cpu: 1000m
        memory: 2Gi

    additionalScrapeConfigs:
      - job_name: timeweb-app-postgres
        scrape_interval: 30s
        scheme: https
        metrics_path: /d2676bd4-e66e-46b2-86c5-73a635f59e90/service/metrics
        basic_auth:
          username: "admin"
          password: "GDbnb^s7>I.Rm."
        static_configs:
          - targets:
              - dbs-exporter.timeweb.cloud:443

      - job_name: timeweb-audit-postgres
        scrape_interval: 30s
        scheme: https
        metrics_path: /03190b4c-1d91-4b21-b8e6-e3e8aa325a12/service/metrics
        basic_auth:
          username: "admin"
          password: "I9VLCJ57r)@fdm"
        static_configs:
          - targets:
              - dbs-exporter.timeweb.cloud:443

      - job_name: timeweb-app-redis-1
        scrape_interval: 30s
        scheme: https
        metrics_path: /ebf82e48-b020-4f37-960f-5ac0fb7454f6/service/metrics
        basic_auth:
          username: "admin"
          password: "Alisa1234"
        static_configs:
          - targets:
              - dbs-exporter.timeweb.cloud:443

      - job_name: timeweb-rabbitmq
        scrape_interval: 30s
        scheme: https
        metrics_path: /766021f5-91ad-458c-a366-683c9a307aa8/service/metrics
        basic_auth:
          username: "admin"
          password: "%7_P1t;wRDuyv{"
        static_configs:
          - targets:
              - dbs-exporter.timeweb.cloud:443

prometheusOperator:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi

kube-state-metrics:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

prometheus-node-exporter:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

defaultRules:
  create: true

kubeApiServer:
  enabled: true

kubeControllerManager:
  enabled: true

kubeScheduler:
  enabled: true

kubeEtcd:
  enabled: false

kubeProxy:
  enabled: true

kubelet:
  enabled: true

crds:
  enabled: false