apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: vm-single
  namespace: victoria-metrics
spec:
  image:
    repository: victoriametrics/victoria-metrics
  replicaCount: 1
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 2Gi
  retentionPeriod: 30d
  serviceSpec:
    spec:
      type: ClusterIP
  storage:
    accessModes:
      - ReadWriteOnce
    storageClassName: nvme.network-drives.csi.timeweb.cloud
    resources:
      requests:
        storage: 30Gi