replicaCount: 1

image:
  repository: ghcr.io/arni1197/audit-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 3000

containerPort: 3000

secretName: secret-audit-service

resources:
  requests:
    cpu: "50m"
    memory: "128Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"