# docker-infra-compose.yml
version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: pg-local
    environment:
      POSTGRES_USER: game_user
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: game_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata_local:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis-local
    ports:
      - "6379:6379"

volumes:
  pgdata_local: