replicaCount: 1

image:
  repository: ghcr.io/arni1197/api-gateway
  tag: sha-9138f6678ba39b3ca56ee488a9ed46b7fb995139
  digest: "sha256:9b985016e7327566a951edc124e4805953d5fb06ea4af74a19182998edab77ed"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: workload
              operator: In
              values:
                - apps
resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false

env:
  NODE_ENV: "development"

secrets:
  envSecretName: secret-api-gateway