replicaCount: 1

image:
  repository: ghcr.io/arni1197/api-gateway
  tag: sha-5e9a5181760f5e6c74e64ac818bee757116bad6a
  digest: "sha256:e6e1ef46ffa8b36fb33cb411154ba1962aeb9a203a3b4e63dbe6ce500f7bc476"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

secrets:
  envSecretName: secret-api-gateway

env:
  NODE_ENV: "development"

automountServiceAccountToken: false

terminationGracePeriodSeconds: 30

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

extraVolumes:
  - name: tmp
    emptyDir: {}

extraVolumeMounts:
  - name: tmp
    mountPath: /tmp
serviceAccount:
  create: true
  name: api-gateway-sa

resources:
  requests:
    cpu: 85m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

readinessProbe:
  httpGet:
    path: /api/health
    port: 3000
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3

livenessProbe:
  httpGet:
    path: /api/health
    port: 3000
  initialDelaySeconds: 15
  periodSeconds: 20
  timeoutSeconds: 2
  failureThreshold: 3

autoscaling:
  enabled: false