replicaCount: 1

image:
  repository: ghcr.io/arni1197/audit-service
  tag: sha-e9cd3d9a538c23725b4418aa6ea01b7481316987
  digest: "sha256:c136b3fcd82be4bd38f145c2f75964ee4a0e9bd294b8b3b1e28ba51d3a6c1622"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

containerPort: 3000

secrets:
  envSecretName: secret-audit-service

env:
  NODE_ENV: "development"
rollout:
  enabled: false
automountServiceAccountToken: false

terminationGracePeriodSeconds: 30

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

extraVolumes:
  - name: tmp
    emptyDir: {}

extraVolumeMounts:
  - name: tmp
    mountPath: /tmp


serviceAccount:
  create: true
  name: audit-service-sa
resources:
  requests:
    cpu: 85m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

readinessProbe:
  httpGet:
    path: /metrics
    port: 3000
  initialDelaySeconds: 40
  periodSeconds: 20
  timeoutSeconds: 2
  failureThreshold: 3

livenessProbe:
  httpGet:
    path: /metrics
    port: 3000
  initialDelaySeconds: 90
  periodSeconds: 20
  timeoutSeconds: 2
  failureThreshold: 3

autoscaling:
  enabled: false