replicaCount: 1

image:
  repository: ghcr.io/arni1197/audit-service
  tag: sha-ff14f1f7b44e10c77b80fca10ae207db965f3e62
  digest: "sha256:a2db3cb7cb3ca904e17586f9ce4cf4489d24260f6ad6446c974aef22b44561a5"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

containerPort: 3000

secrets:
  envSecretName: secret-audit-service



podAnnotations:
  instrumentation.opentelemetry.io/inject-nodejs: jaeger/nodejs-instrumentation


  
env:
  NODE_ENV: "development"
rollout:
  enabled: false
automountServiceAccountToken: false

terminationGracePeriodSeconds: 30

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

extraVolumes:
  - name: tmp
    emptyDir: {}

extraVolumeMounts:
  - name: tmp
    mountPath: /tmp


serviceAccount:
  create: true
  name: audit-service-sa
resources:
  requests:
    cpu: 85m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

readinessProbe:
  httpGet:
    path: /metrics
    port: 3000
  initialDelaySeconds: 40
  periodSeconds: 20
  timeoutSeconds: 2
  failureThreshold: 3

livenessProbe:
  httpGet:
    path: /metrics
    port: 3000
  initialDelaySeconds: 90
  periodSeconds: 20
  timeoutSeconds: 2
  failureThreshold: 3

autoscaling:
  enabled: false