replicaCount: 1

image:
  repository: ghcr.io/arni1197/auth-service
  tag: sha-b23010a616134886a7621249da75a5d9f878487b
  digest: "sha256:0cdc80fc070f5a82bf5ad0672d2755d79c1a8117b13a652ad9cf8995158fdea2"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

secrets:
  envSecretName: secret-auth-service

env:
  NODE_ENV: "development"

automountServiceAccountToken: false

terminationGracePeriodSeconds: 30

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

extraVolumes:
  - name: tmp
    emptyDir: {}

extraVolumeMounts:
  - name: tmp
    mountPath: /tmp

serviceAccount:
  create: true
  name: auth-service-sa

resources:
  requests:
    cpu: 25m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

readinessProbe:
  httpGet:
    path: /api/health
    port: 3000
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3

livenessProbe:
  httpGet:
    path: /api/health
    port: 3000
  initialDelaySeconds: 15
  periodSeconds: 20
  timeoutSeconds: 2
  failureThreshold: 3

autoscaling:
  enabled: false