replicaCount: 1

image:
  repository: ghcr.io/arni1197/auth-service
  tag: sha-b23010a616134886a7621249da75a5d9f878487b
  digest: "sha256:0cdc80fc070f5a82bf5ad0672d2755d79c1a8117b13a652ad9cf8995158fdea2"
  pullPolicy: IfNotPresent
resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: workload
              operator: In
              values:
                - apps

env:
  NODE_ENV: "development"

readinessProbe:
  httpGet:
    path: /api/health
    port: 3000
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3

livenessProbe:
  httpGet:
    path: /api/health
    port: 3000
  initialDelaySeconds: 15
  periodSeconds: 20
  timeoutSeconds: 2
  failureThreshold: 3
autoscaling:
  enabled: false