replicaCount: 1

image:
  repository: ghcr.io/arni1197/catalog-service
  tag: sha-258ad81c0e114a1d8b95876dc5d1946df9b7a5ff
  digest: "sha256:b9d46525f3903a578e9eb6ab25ddb572473aa443bdfbe8604d4864f4f7b1c826"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3003
  targetPort: 3003


serviceAccount:
  create: true
  name: catalog-service-sa

automountServiceAccountToken: false
resources:
  requests:
    cpu: 85m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

env:
  NODE_ENV: "development"

terminationGracePeriodSeconds: 30

readinessProbe:
  httpGet:
    path: /api/health/ready
    port: 3003
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 1

livenessProbe:
  httpGet:
    path: /api/health/live
    port: 3003
  initialDelaySeconds: 15
  periodSeconds: 20
  timeoutSeconds: 2
  failureThreshold: 3

autoscaling:
  enabled: false