replicaCount: 1

image:
  repository: ghcr.io/arni1197/catalog-service
  tag: sha-f0cb389e73c27141610d89677d44e97085eb4efd
  digest: "sha256:bd5a63ef549c79eff8dfcb8e45c2810af548aafdc4b0bc184ed0b42b9dc3b5cc"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3003
  targetPort: 3003


serviceAccount:
  create: true
  name: catalog-service-sa

automountServiceAccountToken: false
resources:
  requests:
    cpu: 85m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

env:
  NODE_ENV: "development"

terminationGracePeriodSeconds: 30

readinessProbe:
  httpGet:
    path: /api/health/ready
    port: 3003
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 1

livenessProbe:
  httpGet:
    path: /api/health/live
    port: 3003
  initialDelaySeconds: 15
  periodSeconds: 20
  timeoutSeconds: 2
  failureThreshold: 3

autoscaling:
  enabled: false