replicaCount: 1

image:
  repository: ghcr.io/arni1197/catalog-service
  tag: sha-b72a5baa3d8fc72e2aab6705777436be9c756429
  digest: "sha256:0c8b28bfb847c0e2837aedf1b0ba32a049da78b4c95ca8399d12bcf46c92519d"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3003

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

env:
  NODE_ENV: "development"
autoscaling:
  enabled: false