replicaCount: 1

image:
  repository: ghcr.io/arni1197/user-service
  # 🏷️ Человеческая версия (удобно смотреть в UI/логах)
  tag: sha-9e2b636577b142e3b7dde4a715e9ab563123a469
  # 🔒 Истина для деплоя (если chart настроен на digest)
  digest: "sha256:06fe265b906ccb4fa42bdc578fc11fa7ebd3fa0d111a5ac0176f6ffb8087b7ae"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

serviceAccount:
  create: true
  name: user-service-sa

autoscaling:
  enabled: false

automountServiceAccountToken: false
resources:
  requests:
    cpu: 85m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

env:
  NODE_ENV: "development"

readinessProbe:
  httpGet:
    path: /api/health
    port: 3000
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3

livenessProbe:
  httpGet:
    path: /api/health
    port: 3000
  initialDelaySeconds: 15
  periodSeconds: 20
  timeoutSeconds: 2
  failureThreshold: 3