replicaCount: 1

image:
  repository: ghcr.io/arni1197/user-service
  # 🏷️ Человеческая версия (удобно смотреть в UI/логах)
  tag: sha-15e9b6ff71914d7e72aa0801e2675c09ead757b8
  # 🔒 Истина для деплоя (если chart настроен на digest)
  digest: "sha256:36223bc73094e60845ac434721de61ae25eafa624506fe2aa186b262f2cb497c"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3002

serviceAccount:
  create: true
  name: user-service-sa

automountServiceAccountToken: false
resources:
  requests:
    cpu: 25m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

env:
  NODE_ENV: "development"

readinessProbe:
  httpGet:
    path: /api/health
    port: 3002
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3

livenessProbe:
  httpGet:
    path: /api/health
    port: 3002
  initialDelaySeconds: 15
  periodSeconds: 20
  timeoutSeconds: 2
  failureThreshold: 3