replicaCount: 1

image:
  repository: ghcr.io/arni1197/user-service
  # 🏷️ Человеческая версия (удобно смотреть в UI/логах)
  tag: sha-d8f1b5b36bbeab51dff3a2aee1a0241c2449a241
  # 🔒 Истина для деплоя (если chart настроен на digest)
  digest: "sha256:69d34f1deb192e2c5b266e706990b031885ba04f9045f2e13c1a836a394e3d08"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

serviceAccount:
  create: true
  name: user-service-sa

autoscaling:
  enabled: false

automountServiceAccountToken: false
resources:
  requests:
    cpu: 85m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

env:
  NODE_ENV: "development"

readinessProbe:
  httpGet:
    path: /api/health
    port: 3000
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3

livenessProbe:
  httpGet:
    path: /api/health
    port: 3000
  initialDelaySeconds: 15
  periodSeconds: 20
  timeoutSeconds: 2
  failureThreshold: 3