apiVersion: batch/v1
kind: Job
metadata:
  name: audit-service-migrate
  namespace: dev
  labels:
    app.kubernetes.io/name: audit-service-migrate
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: audit-service-migrate
    spec:
      restartPolicy: Never

      containers:
        - name: audit-service-migrate
          image: ghcr.io/arni1197/audit-service@sha256:502bda66543961b0038176ac7cf36b23b99d5d8c253b380d21d39948699bf2d9
          imagePullPolicy: IfNotPresent

          envFrom:
            - secretRef:
                name: secret-audit-service

          command:
            - sh
            - -ec
            - |
              echo "🚀 Running audit-service migrations..."
              npx prisma migrate deploy
              echo "✅ Migrations completed"