<!-- trivy-html.tpl -->
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Trivy Report</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Arial, sans-serif; margin: 24px; }
    h1 { margin: 0 0 12px; }
    .meta { color: #555; margin-bottom: 20px; }
    pre { background: #f6f8fa; padding: 16px; border-radius: 8px; overflow: auto; }
    .hint { color: #777; font-size: 12px; margin-top: 12px; }
  </style>
</head>
<body>
  <h1>Trivy Vulnerability Report</h1>
  <div class="meta">
    Generated by Trivy. This is a lightweight HTML wrapper around the report output.
  </div>
  <pre>{{ . | toPrettyJson }}</pre>
  <div class="hint">
    Tip: Use the SARIF upload to view results in GitHub Security tab.
  </div>
</body>
</html>