apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policies
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Arni1197/test-Jenkins.git
    targetRevision: main
    path: k8s/platform/manifests/kyverno-policies

  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true