apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "https://vault.vault.svc:8200"
      path: "kv"
      version: "v2"
      caBundle: |
        -----BEGIN CERTIFICATE-----
        MIIEHjCCAwagAwIBAgIQA5NCFqLcuBep0Y/W9PWIWDANBgkqhkiG9w0BAQsFADAa
        MRgwFgYDVQQDEw92YXVsdC52YXVsdC5zdmMwHhcNMjYwMzE5MDcyNDAwWhcNMjYw
        NjE3MDcyNDAwWjAaMRgwFgYDVQQDEw92YXVsdC52YXVsdC5zdmMwggEiMA0GCSqG
        SIb3DQEBAQUAA4IBDwAwggEKAoIBAQC/NZd3jvBkzToF/jqA8WV/TVKvRYwJsYcO
        tbtBzeZo8iemjXQnXqguedHjWJE8t0gVvHnhZsNrRbf6KP8zV+FPCYPeMMhCfYOL
        Jkyzm7rn0XyEPKZIz9syqNYsoUkCYs4ow8mEfqUtjsjrU9lKnMTL7/NjLcTleJ1N
        Os5zQTgppR7VEkv7MV9yNXeL/5hYUOE/TsowHLbMSVRTbyNXjEj+PoVKZOpXcicg
        a3X6lTH9VarcQFwRjJvICf62b0AA0ChLmRiHqljKxrnILE7vW2wZwqCZuqfHDKEO
        ePog34mEfuZUq2saC7iiv43UIeTQcMWExXIWv57AtnNOKoNNylxRAgMBAAGjggFe
        MIIBWjAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIw
        ADCCASkGA1UdEQSCASAwggEcggV2YXVsdIILdmF1bHQudmF1bHSCD3ZhdWx0LnZh
        dWx0LnN2Y4IddmF1bHQudmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWyCFnZhdWx0LTAu
        dmF1bHQtaW50ZXJuYWyCLnZhdWx0LTAudmF1bHQtaW50ZXJuYWwudmF1bHQuc3Zj
        LmNsdXN0ZXIubG9jYWyCFnZhdWx0LTEudmF1bHQtaW50ZXJuYWyCLnZhdWx0LTEu
        dmF1bHQtaW50ZXJuYWwudmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWyCFnZhdWx0LTIu
        dmF1bHQtaW50ZXJuYWyCLnZhdWx0LTIudmF1bHQtaW50ZXJuYWwudmF1bHQuc3Zj
        LmNsdXN0ZXIubG9jYWwwDQYJKoZIhvcNAQELBQADggEBAEUugidYgnTvlK21qX26
        pUlDjx7t6pGPu319LEIB82nGHTpt6ETH6x3skp0pw85k3JkV/GNzSHgwxpdvA9xx
        zjxkAOjeTVS+s1/wQNdJ2rEom2HYKMZC1qBPZPrn5aA2e77CAuOOce3rrWTUaWIZ
        Sje/RBAyWl6f7kcfApp+Ksltk/Crul4069dw+zAUt+5J0igd19tfQg0BG5TAdpmv
        r/6I8Av7VoLyfbJPh6Dp/KG6FlxWd+iC7QTWgP7MBLHy8/NM8kOYFUjwERpZa+jh
        zXferABqnuVyQOBux4ZjlsEXagdpPlTqXSGE/fCUnc2Qzh6YuHoKTEk6OhFwRZQh
        bdg=
        -----END CERTIFICATE-----
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "external-secrets-role"
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets