apiVersion: v1
kind: Secret
metadata:
  name: additional-scrape-managed-kafka
  namespace: kube-prometheus-stack
type: Opaque
stringData:
  additional-scrape-configs.yaml: |
    - job_name: managed-kafka-jmx
      scheme: https
      metrics_path: /10207d2e-fa29-49e7-8902-38ef0757c031/service/metrics
      basic_auth:
        username: admin
        password: '~wW@NO3,LtZ,NW'
      static_configs:
        - targets:
            - dbs-exporter.timeweb.cloud