apiVersion: v1
kind: Secret
metadata:
  name: timeweb-app-postgres-auth
  namespace: kube-prometheus-stack
type: Opaque
stringData:
  username: "admin"
  password: "GDbnb^s7>I.Rm."
---
apiVersion: v1
kind: Secret
metadata:
  name: timeweb-audit-postgres-auth
  namespace: kube-prometheus-stack
type: Opaque
stringData:
  username: "admin"
  password: "I9VLCJ57r)@fdm"
---
apiVersion: v1
kind: Secret
metadata:
  name: timeweb-app-redis-auth
  namespace: kube-prometheus-stack
type: Opaque
stringData:
  username: "admin"
  password: "Alisa1234"
---
apiVersion: v1
kind: Secret
metadata:
  name: timeweb-rabbitmq-auth
  namespace: kube-prometheus-stack
type: Opaque
stringData:
  username: "admin"
  password: "%7_P1t;wRDuyv{"