apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: game-project-staging
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: game-project-staging

  source:
    repoURL: https://github.com/Arni1197/test-Jenkins.git
    targetRevision: HEAD
    path: k8s
    helm:
      valueFiles:
        - values-game-project-staging.yaml

  syncPolicy:
    syncOptions:
      - PruneLast=true
    # Хочешь авто-синк — потом можно включить:
    # automated:
    #   prune: true
    #   selfHeal: true