apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: game-project-staging
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Arni1197/test-Jenkins.git
    targetRevision: main            # 👈 исправили
    path: k8s                       # 👈 путь правильный
    helm:
      valueFiles:
        - values-game-project-staging.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: game-project-staging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true