apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: game-project-prod
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: game-project-prod

  source:
    repoURL: https://github.com/Arni1197/test-Jenkins.git
    targetRevision: HEAD
    path: k8s
    helm:
      valueFiles:
        - values-game-project-prod.yaml

  syncPolicy:
    syncOptions:
      - PruneLast=true
    # automated:
    #   prune: true
    #   selfHeal: true