replicaCount: 2

image:
  repository: ghcr.io/arni1197/api-gateway
  tag: sha-572aa988fc4a0519a4403a598236d3fa161d05f1
  digest: "sha256:0b59d85eacdd7d6aad34872c8364decc54bc35274824f8384a66b237ff720a51"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000

secrets:
  envSecretName: secret-api-gateway



affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: workload
              operator: In
              values:
                - apps

resources:
  requests:
    cpu: 500m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 500Mi

env:
  NODE_ENV: "staging"

serviceAccount:
  create: true
  name: api-gateway-sa



terminationGracePeriodSeconds: 30

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

extraVolumes:
  - name: tmp
    emptyDir: {}
  - name: projected-demo
    projected:

      sources:

        - configMap:

            name: app-config

        - configMap:

            name: app-info

  - name: podinfo
    downwardAPI:
      items:
        - path: pod-name
          fieldRef:
            fieldPath: metadata.name
        - path: namespace
          fieldRef:
            fieldPath: metadata.namespace
        - path: labels
          fieldRef:
            fieldPath: metadata.labels
        - path: uid
          fieldRef:
            fieldPath: metadata.uid

extraVolumeMounts:
  - name: tmp
    mountPath: /tmp

  - name: projected-demo

    mountPath: /etc/projected

    readOnly: true
  - name: podinfo
    mountPath: /etc/podinfo
    readOnly: true

readinessProbe:
  httpGet:
    path: /api/health
    port: 3000
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3

livenessProbe:
  httpGet:
    path: /api/health
    port: 3000
  initialDelaySeconds: 15
  periodSeconds: 20
  timeoutSeconds: 2
  failureThreshold: 3

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 65