replicaCount: 1

image:
  repository: ghcr.io/arni1197/api-gateway
  tag: sha-758b8798a056b971841236f052d3bce0903ed809
  digest: "sha256:fa3bf77963239e70552589a150920b324dbc0b138f946d327185f5ae0ac2845e"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000
  targetPort: 3000


affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: workload
              operator: In
              values:
                - apps
resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi
autoscaling:
  enabled: true


env:
  NODE_ENV: "staging"