replicaCount: 2

image:
  repository: ghcr.io/arni1197/catalog-service
  tag: sha-6159537ebed5dd5646f50496f9f6f7ac46d3ded6
  digest: "sha256:1107ec4db8f26b882620c362b81242d7cd419fedf465fc3660833efb4a805bf8"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3003
  targetPort: 3003

secrets:
  envSecretName: secret-catalog-service

env:
  NODE_ENV: "staging"

serviceAccount:
  create: true
  name: secret-catalog-service

automountServiceAccountToken: false

terminationGracePeriodSeconds: 30

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

extraVolumes:
  - name: tmp
    emptyDir: {}

extraVolumeMounts:
  - name: tmp
    mountPath: /tmp

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: workload
              operator: In
              values:
                - apps

resources:
  requests:
    cpu: 128m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

readinessProbe:
  httpGet:
    path: /api/health/ready
    port: 3003
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3

livenessProbe:
  httpGet:
    path:  /api/health/live
    port: 3003
  initialDelaySeconds: 15
  periodSeconds: 20
  timeoutSeconds: 2
  failureThreshold: 3

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 65