replicaCount: 2

image:
  repository: ghcr.io/arni1197/catalog-service
  tag: sha-258ad81c0e114a1d8b95876dc5d1946df9b7a5ff
  digest: "sha256:b9d46525f3903a578e9eb6ab25ddb572473aa443bdfbe8604d4864f4f7b1c826"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3003
  targetPort: 3003

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: workload
              operator: In
              values:
                - apps

resources:
  requests:
    cpu: 200m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi

env:
  NODE_ENV: "staging"

terminationGracePeriodSeconds: 30

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

containerSecurityContext:
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL



readinessProbe:
  httpGet:
    path: /api/health/ready
    port: 3003
  initialDelaySeconds: 60
  periodSeconds: 5
  timeoutSeconds: 2
  failureThreshold: 5

livenessProbe:
  httpGet:
    path: /api/health/live
    port: 3003
  initialDelaySeconds: 60
  periodSeconds: 20
  timeoutSeconds: 2
  failureThreshold: 5

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70