apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-service
  labels:
    app: audit-service
spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: audit-service

  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-nodejs: "jaeger/nodejs-instrumentation"
      labels:
        app: audit-service

    spec:
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: audit-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.containerPort }}

          env:
            - name: OTEL_SERVICE_NAME
              value: "audit-service"

          envFrom:
            - secretRef:
                name: {{ .Values.secretName }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}