apiVersion: v1
kind: Service
metadata:
  name: audit-service
  labels:
    app.kubernetes.io/name: audit-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: audit-service
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}