apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: game
  namespace: kong
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - game.90.156.210.86.nip.io
      secretName: game
  rules:
    - host: game.90.156.210.86.nip.io
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: kong-kong-proxy
                port:
                  number: 80