apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secret-catalog-service
  namespace: staging
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: secret-catalog-service
    creationPolicy: Owner
    deletionPolicy: Retain
  dataFrom:
    - extract:
        key: kv/app/staging/catalog-service