apiVersion: v1
kind: Secret
metadata:
  name: additional-scrape-configs
  namespace: kube-prometheus-stack
type: Opaque
stringData:
  additional-scrape-configs.yaml: |
    - job_name: "timeweb-app-postgres"
      scheme: https
      metrics_path: /d2676bd4-e66e-46b2-86c5-73a635f59e90/service/metrics
      static_configs:
        - targets:
            - "dbs-exporter.timeweb.cloud:443"
      basic_auth:
        username: "admin"
        password: "GDbnb^s7>I.Rm."

    - job_name: "timeweb-audit-postgres"
      scheme: https
      metrics_path: /03190b4c-1d91-4b21-b8e6-e3e8aa325a12/service/metrics
      static_configs:
        - targets:
            - "dbs-exporter.timeweb.cloud:443"
      basic_auth:
        username: "admin"
        password: "I9VLCJ57r)@fdm"

    - job_name: "timeweb-app-redis-1"
      scheme: https
      metrics_path: /ebf82e48-b020-4f37-960f-5ac0fb7454f6/service/metrics
      static_configs:
        - targets:
            - "dbs-exporter.timeweb.cloud:443"
      basic_auth:
        username: "admin"
        password: "Alisa1234"

    - job_name: "timeweb-rabbitmq"
      scheme: https
      metrics_path: /766021f5-91ad-458c-a366-683c9a307aa8/service/metrics
      static_configs:
        - targets:
            - "dbs-exporter.timeweb.cloud:443"
      basic_auth:
        username: "admin"
        password: "%7_P1t;wRDuyv{"