apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-gateway-prod
  namespace: kube-prometheus-stack
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - prod
  selector:
    matchLabels:
      app.kubernetes.io/name: api-gateway
  endpoints:
    - port: http
      path: /api/metrics
      interval: 15s
      scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: auth-service-prod
  namespace: kube-prometheus-stack
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - prod
  selector:
    matchLabels:
      app.kubernetes.io/name: auth-service
  endpoints:
    - port: http
      path: /api/metrics
      interval: 15s
      scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: user-service-prod
  namespace: kube-prometheus-stack
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - prod
  selector:
    matchLabels:
      app.kubernetes.io/name: user-service
  endpoints:
    - port: http
      path: /api/metrics
      interval: 15s
      scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: catalog-service-prod
  namespace: kube-prometheus-stack
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - prod
  selector:
    matchLabels:
      app.kubernetes.io/name: catalog-service
  endpoints:
    - port: http
      path: /api/metrics
      interval: 15s
      scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: audit-service-prod
  namespace: kube-prometheus-stack
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - prod
  selector:
    matchLabels:
      app.kubernetes.io/name: audit-service
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s