apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-gateway
  namespace: kube-prometheus-stack
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - dev
  selector:
    matchLabels:
      app.kubernetes.io/name: api-gateway
  endpoints:
    - port: http
      path: /api/metrics
      interval: 15s
      scrapeTimeout: 10s