apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: audit-service-staging
  namespace: kube-prometheus-stack
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - staging
  selector:
    matchLabels:
      app.kubernetes.io/name: audit-service
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s