{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default "catalog-service-sa" | quote }}
  labels:
    app.kubernetes.io/name: catalog-service
automountServiceAccountToken: {{ .Values.automountServiceAccountToken | default false }}
{{- end }}