global:
  enabled: true
  tlsDisable: false

injector:
  enabled: true
  replicas: 1
  authPath: "auth/kubernetes"
  webhook:
    failurePolicy: Ignore
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "250m"
      memory: "256Mi"

server:
  enabled: true
  updateStrategyType: "OnDelete"

  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1Gi"

  extraEnvironmentVars:
    VAULT_CACERT: /vault/userconfig/vault-server-tls/ca.crt
    VAULT_TLSCERT: /vault/userconfig/vault-server-tls/tls.crt
    VAULT_TLSKEY: /vault/userconfig/vault-server-tls/tls.key

  extraVolumes:
    - type: secret
      name: vault-server-tls

  dataStorage:
    enabled: true
    size: 10Gi
    mountPath: "/vault/data"
    storageClass: "nvme.network-drives.csi.timeweb.cloud"
    accessMode: ReadWriteOnce

  auditStorage:
    enabled: true
    size: 10Gi
    mountPath: "/vault/audit"
    storageClass: "nvme.network-drives.csi.timeweb.cloud"
    accessMode: ReadWriteOnce

  dev:
    enabled: false

  standalone:
    enabled: false

  ha:
    enabled: true
    replicas: 3

    raft:
      enabled: true
      setNodeId: true
      config: |-
        ui = true

        listener "tcp" {
          address = "[::]:8200"
          cluster_address = "[::]:8201"

          tls_cert_file = "/vault/userconfig/vault-server-tls/tls.crt"
          tls_key_file = "/vault/userconfig/vault-server-tls/tls.key"
          tls_client_ca_file = "/vault/userconfig/vault-server-tls/ca.crt"
        }

        storage "raft" {
          path = "/vault/data"
        }

        service_registration "kubernetes" {}

  service:
    enabled: true

  readinessProbe:
    enabled: true
    port: 8200

ui:
  enabled: true
  serviceType: "ClusterIP"

csi:
  enabled: false